name: 🚀 mdbook 持续集成

on:
  push:
    branches:
      - master
    paths:
      - "mianzha/**"

jobs:
  mianzha:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🍌 克隆公有仓库 testmdbook 到虚拟机的 public-repo 文件夹
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/vongdefu/testmdbook.git public-repo

      - name: 🍒 同步 private-repo 和 public-repo ， 并推送到 vongdefu.github.io
        run: |
          rsync -av --delete --exclude=".*" mianzha/ public-repo/src/
          cd public-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Trigger: ${{ github.sha }}， ${{ github.event.head_commit.message }} "
          git push origin master





